name: Angular CI Pipeline

on:
  push:
    branches:
      - main  # ou 'master', conforme o seu branch principal
  pull_request:
    branches:
      - main  # ou 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Usando Ubuntu para rodar o pipeline

    steps:
    # Passo 1: Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Passo 2: Configurar o Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ou qualquer versão que você esteja usando no seu projeto

    # Passo 3: Instalar as dependências
    - name: Install dependencies
      run: |
        npm install

    # Passo 4: Rodar os testes unitários
    - name: Run unit tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadlessCI

    # Passo 5: Rodar a build do Angular
    - name: Build Angular app
      run: |
        npm run build --prod  # Executa o build de produção do Angular

    # Passo 6: Verificar se a build foi bem-sucedida
    - name: Check build success
      run: |
        if [ ! -f dist/your-app/index.html ]; then
          echo "Build failed!"
          exit 1
        fi
